version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: carteira-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carteira_financeira
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build: .
    container_name: carteira-api
    command: >
      sh -c "sleep 5 &&
         npx prisma generate &&
         npx prisma migrate deploy &&
         npm run start:dev"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network: